version: "3.8"
services:
  crawler:
    container_name: dm-1-crawler
    build: ./crawler
    environment:
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_PORT
  db:
    container_name: dm-1-db
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_PORT
      - TZ=Europe/Berlin
    ports:
      - "32753:3306"